import argparse
from pathlib import Path

import h5py
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, FFMpegWriter, PillowWriter
import numpy as np


def load_fields(h5_path: Path):
    with h5py.File(h5_path, "r") as f:
        f_values = f["fields/f/value"][:]
        times = f["fields/f/time"][:]
        x_min = float(f["parameters/xmin"][()])
        x_max = float(f["parameters/xmax"][()])
        v_min = float(f["parameters/vmin"][()])
        v_max = float(f["parameters/vmax"][()])

    return f_values, times, (x_min, x_max, v_min, v_max)


def create_video(h5_file: Path, output: Path, fps: int = 20, dpi: int = 120, cmap: str = "viridis"):
    values, times, extent = load_fields(h5_file)

    fig, ax = plt.subplots(figsize=(7, 4.8))
    im = ax.imshow(
        values[0].T,
        origin="lower",
        aspect="auto",
        extent=extent,
        cmap=cmap,
        interpolation="nearest",
    )
    ax.set_xlabel("x")
    ax.set_ylabel("v")
    title = ax.set_title(f"Distribution f(x, v), t = {times[0]:.4f}")
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label("f")

    def update(frame_index: int):
        im.set_data(values[frame_index].T)
        title.set_text(f"Distribution f(x, v), t = {times[frame_index]:.4f}")
        return im, title

    anim = FuncAnimation(fig, update, frames=values.shape[0], interval=1000 / fps, blit=False)

    output.parent.mkdir(parents=True, exist_ok=True)
    suffix = output.suffix.lower()
    if suffix == ".gif":
        writer = PillowWriter(fps=fps)
    else:
        writer = FFMpegWriter(fps=fps)

    anim.save(str(output), writer=writer, dpi=dpi)
    plt.close(fig)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create an animation of f(x, v, t) from HMF Vlasov HDF5 output.")
    parser.add_argument("input", type=Path, help="Path to hmf.h5 generated by hmf_vlasov.py")
    parser.add_argument("--output", type=Path, default=Path("distribution.mp4"), help="Output video path (.mp4 or .gif)")
    parser.add_argument("--fps", type=int, default=20, help="Frames per second")
    parser.add_argument("--dpi", type=int, default=120, help="Output DPI")
    parser.add_argument("--cmap", default="viridis", help="Matplotlib colormap")
    args = parser.parse_args()

    create_video(args.input, args.output, fps=args.fps, dpi=args.dpi, cmap=args.cmap)
